prefix rdfs:<http://www.w3.org/2000/01/rdf-schema#>
prefix rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>

prefix rapp:<http://redfoot.net/04/26/rapp/>

load rdf_app.rdf http://localhost/


server :9090
add_app rdf_app.RDFApp

redcode on
server :9091
add_app generic.GenericApp

#start_node rdf_app :9092

#!tell_redfoot = lambda s, p, o: edge.tell("redfoot/2002/05/01/ add %s %s %s" % (s, p, o))

#visit tell_redfoot ANY ANY ANY